name: go-ovirt-client compilation with current patch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  compile-and-build-rpm:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8
    steps:
      - name: prepare env
        run: |
           yum install -y git createrepo_c rpm-build golang make
      - name: Checkout
        uses: actions/checkout@v3
      - name : Compile go-ovirt-client tests and Build go-ovirt-client-tests RPM
        run: |
          echo "::group::Generating suffix..."
          SUFFIX=.$(date -u +%Y%m%d%H%M%S).git$(git rev-parse --short HEAD)
          echo "::endgroup::"

          mkdir -p go-ovirt-client-tests-bin
          go test -v -c -o go-ovirt-client-tests-bin/go-ovirt-client-tests-exe

          mkdir -p BUILDROOT SOURCES
          cp go-ovirt-client-tests-bin/go-ovirt-client-tests-exe SOURCES/
          tar cvzf go-ovirt-client-tests.tar.gz go-ovirt-client-tests-bin/
          cp go-ovirt-client-tests.tar.gz SOURCES
          rpmbuild -D "_topdir $(pwd)" -D "release_suffix ${SUFFIX}" -bb go-ovirt-client-tests.spec
      - name: Collect artifacts
        run: |
          mkdir -p exported-artifacts
          find . -iname \*rpm -exec mv "{}" exported-artifacts/ \;
          ls -l exported-artifacts
      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@main
        with:
          directory: exported-artifacts
